version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/share/nginx.conf:/etc/nginx/nginx.conf
      - /opt/share/static:/usr/share/nginx/html
    networks:
      - webnet

  core:
    image: justify242/art-core:latest
    container_name: core
    entrypoint: [ "/bin/bash", "entrypoint.sh" ]
    volumes:
      - /opt/share/media:/app/media
      - /opt/share/static:/app/static
      - /opt/share/.env:/app/.env
    ports:
      - "8000:8000"
    networks:
      - webnet

  redis:
    image: redis:latest
    networks:
      - webnet

  huey:
    image: justify242/art-core:latest
    container_name: huey
    entrypoint: [ "python", "manage.py", "run_huey" ]
    volumes:
      - /opt/share/media:/app/media
      - /opt/share/static:/app/static
      - /opt/share/.env:/app/.env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge