# Generated by Django 5.2.4 on 2025-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatoroption',
            name='calculator',
        ),
        migrations.AddField(
            model_name='calculator',
            name='options',
            field=models.ManyToManyField(to='core.calculatoroption'),
        ),
    ]
