# Generated by Django 5.2.4 on 2025-07-21 08:45

from django.db import migrations, models


def set_slug(apps, schema_editor):
    from unidecode import unidecode
    from django.utils.text import slugify

    model = apps.get_model("core", "product")

    for obj in model.objects.all():
        obj.slug = slugify(unidecode(obj.name))
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_slug_alter_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(set_slug)
    ]
