# Generated by Django 5.2.4 on 2025-07-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calculatoroption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calculatoroptionchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
