# Generated by Django 5.2.4 on 2025-07-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparameter',
            name='note',
            field=models.TextField(default=1, verbose_name='Примечание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderparameter',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calculatoroption', verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='orderparameter',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calculatoroptionchoice', verbose_name='Значение'),
        ),
    ]
