# Generated by Django 5.2.4 on 2025-07-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderparameter_note_alter_orderparameter_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderparameter',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
