# Generated by Django 5.2.4 on 2025-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderparameter_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparameter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/'),
        ),
    ]
