# Generated by Django 5.2.4 on 2025-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderparameter_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatoroption',
            name='field_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование поля'),
        ),
        migrations.AlterField(
            model_name='orderparameter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/', verbose_name='Вложение'),
        ),
    ]
