# Generated by Django 5.2.4 on 2025-07-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calculatoroption_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='options',
        ),
    ]
