# Generated by Django 5.2.4 on 2025-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='calculatoroption',
            options={'verbose_name': 'Параметр калькулятора', 'verbose_name_plural': 'Параметры калькуляторов'},
        ),
        migrations.AlterModelOptions(
            name='calculatoroptionchoice',
            options={'verbose_name': 'Значение параметра калькулятора', 'verbose_name_plural': 'Значения параметров калькуляторов'},
        ),
        migrations.AlterModelOptions(
            name='orderparameter',
            options={'verbose_name': 'Параметр заказа', 'verbose_name_plural': 'Параметры заказов'},
        ),
    ]
