# Generated by Django 5.2.4 on 2025-09-17 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feedback_alter_calculatoroption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок вопроса')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', ckeditor.fields.RichTextField(max_length='Описание')),
            ],
            options={
                'verbose_name': 'Технология нанесения',
                'verbose_name_plural': 'Технологии нанесения',
            },
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='options',
        ),
        migrations.RemoveField(
            model_name='product',
            name='calculator',
        ),
        migrations.RemoveField(
            model_name='calculatoroptionchoice',
            name='option',
        ),
        migrations.RemoveField(
            model_name='orderparameter',
            name='option',
        ),
        migrations.RemoveField(
            model_name='orderparameter',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='orderfiles',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderparameter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=1, max_length=100, verbose_name='Контакт пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Тираж'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='ФИО пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.TextField(default=1, verbose_name='Тип изделия'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Calculator',
        ),
        migrations.DeleteModel(
            name='CalculatorOption',
        ),
        migrations.DeleteModel(
            name='CalculatorOptionChoice',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='OrderFiles',
        ),
        migrations.DeleteModel(
            name='OrderParameter',
        ),
    ]
