# Generated by Django 5.2.4 on 2025-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_case_alter_technology_description_caseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseimage',
            options={'verbose_name': 'Изображение кейса', 'verbose_name_plural': 'Изображения кейсов'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(default=1, verbose_name='Комментарий к заказу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='telegram',
            field=models.CharField(default=1, max_length=100, verbose_name='Ник в Telegram'),
            preserve_default=False,
        ),
    ]
