# Generated by Django 5.2.4 on 2025-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_caseimage_options_remove_order_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='privacy_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласен с политикой обработки данных'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
    ]
