# Generated by Django 5.2.4 on 2025-10-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_privacy_terms_accepted_alter_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Кейс опубликован'),
        ),
    ]
