# Generated by Django 5.2.4 on 2025-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_case_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник в Telegram'),
        ),
    ]
